export const Counries=[
    {
        name:'Ethiopia',
        city:[
            "Addis Ababa",
            "Gonger",
            "Mekele",
            "Jemima"
        ]
    },
    {
        name:'Sweden',
        city:[
            "Stockholm",
            "Uppsala",
            "Örbro",
            "Västras"
        ]
    },
    {
        name:'Norway',
        city:[
            "Oslo",
            "Sala",
            "okösbrg",
            "Jemima"
        ]
    }
] 